name: Aula de GCS (PUC CAMPINAS)

on: push

defaults:
  run:
    shell: bash
    #working-directory: 

jobs:
  primeiro:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar rodando
        run: echo "${{ github.event_name }} foi disparado"
      - name: Mostrar rodando 2
        run: echo teste
    
  segundo:
    name: Segundo
    runs-on: windows-latest
    steps:
      - name: Criando Variaveis de ambiente
        env:
          VAR1: Isto é
          VAR2: GitHub Actions
        run: echo $VAR1 $VAR2
        
  terceiro:
    runs-on: ubuntu-latest
    steps:
      - name: Terceiro
        run: |
          echo "${{ github.event_name }} foi disparado"
          echo " No ${{ runner.os }}"
    

